### ISSUE TITLE
shape of clg.coef_

### ISSUE THREAD

**Issue by prateekagrawal06** [iit-cs579/main#100]
print type(clf.coef_) 
print clf.coef_.shape
<type 'numpy.ndarray'> 
(1, 4734)

M getting (1,4735) instead of (1,4734)
what might be the possible reason for this?

**Comment by mamtakanvinde** [comment]
Me too ! I am also getting 4735

**Comment by prateekagrawal06** [comment]
please let me know if u r able to rectify it..thanks

**Comment by mamtakanvinde** [comment]
Are you getting the classifier output correctly when you fit it with new values?
I am getting
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, penalty='l2', random_state=None, tol=0.0001)

instead of 
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=42, solver='liblinear', tol=0.0001,
          verbose=0)

**Comment by aronwc** [comment]
I think this has something to do with how we treat non-ascii characters. Stay tuned; I'll send an update later tonight.

**Comment by nico401** [comment]
I have the same model parameters :

```python
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          penalty='l2', random_state=42, solver='liblinear', tol=0.0001,
          verbose=0)
```

but the same result for `clf.coef_.shape`:

```python
 <type 'numpy.ndarray'> (1, 4735)
```

**Comment by aronwc** [comment]
There is a discrepancy in how regular expressions work with UTF-8. To keep things simple, let's just assume non-ascii characters (e.g., é) are classified as "punctuation." I've updated the notebook with the following block to test your tokenizers:

```python
# To keep things simple, we'll pretend that non-ascii 
# characters are punctuation.
nonascii_string = u'not the fiancée of not Henri'
print nonascii_string
print('tokenize: %s' % 
      ', '.join(tokenize(nonascii_string)))
print('tokenize_with_punct: %s' %
      ', '.join(tokenize_with_punct(nonascii_string)))
print('tokenize_with_not: %s' %
      ', '.join(tokenize_with_not(nonascii_string)))
```
which produces
```
not the fiancée of not Henri
tokenize: not, the, fianc, e, of, not, henri
tokenize_with_punct: not, the, fianc, é, e, of, not, henri
tokenize_with_not: not, not_the, not_fianc, é, e, of, not, not_henri
```

I've also added this comment to the tokenize instructions:
```
UPDATE: To be more specific, a token is a sequence of 
    alphanumeric characters, i.e., [A-Za-z0-9_]. Non-ascii characters
    are not considered to be part of tokens.
```

So, you may find it easiest to use a regular expression with the [findall method](https://docs.python.org/2/library/re.html#re.findall), rather than splitting on all possible non-alpha-numerics.

Note that none of the expected outputs have changed. I've just given you some more examples to test your code.

**Comment by aronwc** [comment]
Check that you are not retaining newline characters.

```python
tokenize_with_punct(u'hi there\n how are you?')
[u'hi', u'there', u'how', u'are', u'you', u'?']

tokenize_with_punct(u'hi there \x85 how are you?')
[u'hi', u'there', u'how', u'are', u'you', u'?']

tokenize_with_punct(u'hi there \r how are you?')
[u'hi', u'there', u'how', u'are', u'you', u'?']
```

**Comment by jaydeeppatel1701** [comment]
till i was not using non-ascii range i was getting output print clf.coef_.shape = (1,4730)
When i add this range [^\x00-\x7F] in tokenize_with_punct my output is clf.coef_.shape = (1,4805) 
can you be specific with this range??

**Comment by aronwc** [comment]
The regex `\w` should contain the desired range of characters for
alphanumerics.

`\W` should match the range of non-alphanumerics.

All whitespace should be ignore.

Does your code work properly on the non-ascii example?

**Comment by jaydeeppatel1701** [comment]
yes it is working perfectly fine for non-ascii example. I was getting perfect output for do_expt(.... tokenizer_fn=tokenize_with_punct) (except while calculating mean it was showing 0.745 instead of 0.74499999999999988 while all files accuracy was 0.74499999999999988). 
But now i am not. I am sure the problem is with tokenize_with_punct and tokenize_with_not.
Now i am getting tokenizer_expt = [0.73999999999999999, 0.73250000000000004, 0.73499999999999999]

**Comment by poojamankani** [comment]
Hello,

My program is producing results as posted above for nonascii_string = u'not the fiancée of not Henri'. However, the shape of clf.coef_ is 4735. 

Moreover, for the test case "tokenize_with_punct(u'hi there \x85 how are you?')" the program produces the result as "[u'hi', u'there', u'\x85', u'how', u'are', u'you', u'?']"

Also, when I try to handle the \x85 character by setting the UNICODE flag, the tokenize_with_punct(u'hi there \x85 how are you?') returns the result as "[u'hi', u'there', u'how', u'are', u'you', u'?']" but in that case the other experiments return incorrect results and the shape returned is 4733.

**Comment by pavithrachandrakasu** [comment]
Hello,

I am getting something like below:

<type 'numpy.ndarray'>
(1L, 4734L)

Testing of tokenizers block is working fine for me. But not sure why extra character 'L' is getting appended.

**Comment by aronwc** [comment]
'L' just means long (as opposed to int). That's fine.

Here's another example to help:
```python
nonascii_string = u'énot the\x85fiancéée-\n\rof not Henrié '
print 'tokenize:', tokenize(nonascii_string)
print 'with punct:', tokenize_with_punct(nonascii_string)
print 'with not:', tokenize_with_not(nonascii_string)
# \n \r and \x85 are newlines
# é is non-ASCII (\xe9)


tokenize: [u'not', u'the', u'fianc', u'e', u'of', u'not', u'henri']
with punct: [u'\xe9', u'not', u'the', u'fianc', u'\xe9', u'\xe9', u'e', u'-', u'of', u'not', u'henri', u'\xe9']
with not: [u'\xe9', u'not', u'not_the', u'not_fianc', u'\xe9', u'\xe9', u'e', u'-', u'of', u'not', u'not_henri', u'not_\xe9']
```

**Comment by jaydeeppatel1701** [comment]
i think this depends on which punctuations and non-ascii characters we consider in tokenizer_with_punct function. i got the answer for clf.coef_ (1,4734) but didn't get accuracy as shown in assignment and i got [0.73999999999999999, 0.75, 0.74750000000000005].

when i used string.punctuation i was getting clf.coef_ (1,4805) something.
Now i am using these punctuations  .,'*!? and non-ascii character \xe9 and i am getting  clf.coef_ (1,4734) but i am getting above output as i haven't considered -. If i consider - than my output is  clf.coef_ (1,4737) with above mentioned accuracies.

So. please it will be really helpful if you give (because i have wasted plenty of time to figure this out) which punctuations and non-ascii characters we have to consider so we can get output as you said.
Thanks

**Comment by aronwc** [comment]
@jaydeeppatel1701 Check your code into github and I'll take a look.

If you got (1, 4734), then odds are your tokenizer is fine. Something may be wrong with `do_expt` or `do_cross_validation`

**Comment by jaydeeppatel1701** [comment]
Hi professor,
I haven't considered '-' in my tokenizer then I was able to get (1,4734). I have uploaded the assignment.

**Comment by aronwc** [comment]
@jaydeeppatel1701 So you're getting the correct output now?

**Comment by jaydeeppatel1701** [comment]
Nope. Still getting the wrong accuracy

**Comment by aronwc** [comment]
@jaydeeppatel1701 Two things:
- No need to call `repeatable_shuffle` from `do_expt`. `repeatable_shuffle` is called once to set `X, y, filenames` in the earlier cell.
- You have a for loop in `do_expt` that loops over files. This is already done by `do_vectorize`, so this is not needed here (and it will run a lot faster without that loop!). Just pass `filenames` to `do_vectorize`.

**Comment by sdutta9** [comment]
Hello Professor like @jaydeeppatel1701 i got the answer for clf.coef_ (1,4734) but didn't get accuracy as shown in assignment and i got [0.73999999999999999, 0.745, 0.74749999999999994] instead of [0.73999999999999999, 0.74499999999999988, 0.74749999999999994]. Is that fine? I have uploaded my assignment with later functions as well. Can you please guide me at which place I am going wrong as I am not able to figure that out.

**Comment by aronwc** [comment]
That should be fine. Just a rounding error.

**Comment by jaydeeppatel1701** [comment]
Still stuck with the tokenize_with_punct. It was gic=ving me perfect output for clf.coef_ and all tokenize accuracy. But for min_df and max_df it is not working. Actually though i was able to get perfect output for above two, I looked into tokenizing the strings. It is not seperating ascii and non-ascii characters.

**Comment by nico401** [comment]
In my case, both `[A-Za-z0-9_]`and `\w+` produce the output with newlines : 

    python
    [u'hi', u'there', u'\n', u'how', u'are', u'you', u'?']
    [u'hi', u'there', u'\x85', u'how', u'are', u'you', u'?']
    [u'hi', u'there', u'\r', u'how', u'are', u'you', u'?']

**Comment by dmartiinez** [comment]
I am getting (1, 4735) as well and all my other code matches the expected output, not sure what is wrong.

**Comment by FatemaT** [comment]
Did you check tokenize with punct method? Make sure it satisfies all the
test cases given on github here by the professor

On Sunday, November 8, 2015, dmartiinez <notifications@github.com> wrote:

> I am getting (1, 4735) as well and all my other code matches the expected
> output, not sure what is wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iit-cs579/main/issues/100#issuecomment-154797185>.
>


-- 
*Fatima Alteneiji*

*United Arab Emirates University TA*

**Comment by dmartiinez** [comment]
I get this...not sure why..

tokenize: [u'not', u'the', u'fianc', u'e', u'of', u'not', u'henri']
with punct: [u'\xe9not', u'the', u'fianc\xe9\xe9e', u'-', u'of', u'not', u'henri\xe9']
with not: [u'\xe9not', u'the', u'fianc\xe9\xe9e', u'-', u'of', u'not', u'not_henri\xe9']

**Comment by FatemaT** [comment]
So you need to check you tokenize with punct method , and make sure it
return the needed results then you will get the right shape

On Sunday, November 8, 2015, dmartiinez <notifications@github.com> wrote:

> I get this...not sure why..
>
> tokenize: [u'not', u'the', u'fianc', u'e', u'of', u'not', u'henri']
> with punct: [u'\xe9not', u'the', u'fianc\xe9\xe9e', u'-', u'of', u'not',
> u'henri\xe9']
> with not: [u'\xe9not', u'the', u'fianc\xe9\xe9e', u'-', u'of', u'not',
> u'not_henri\xe9']
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iit-cs579/main/issues/100#issuecomment-154802800>.
>


-- 
*Fatima Alteneiji*

*United Arab Emirates University TA*

**Comment by dmartiinez** [comment]
Just did, getting all the sam output but still getting (1, 4735)

**Comment by dmartiinez** [comment]
fixed it!

**Comment by FatemaT** [comment]
Great

On Sunday, November 8, 2015, dmartiinez <notifications@github.com> wrote:

> fixed it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iit-cs579/main/issues/100#issuecomment-154804313>.
>


-- 
*Fatima Alteneiji*

*United Arab Emirates University TA*
