### ISSUE TITLE
Getting wrong list of probabilities for get_top_errors()

### ISSUE THREAD

**Issue by nishu2901** [iit-cs579/main#111]
0.9961346786 194 data\test\pos\9713_8.txt
0.980283290825 115 data\test\pos\4742_10.txt
0.957679961789 305 data\test\neg\479_3.txt
0.922127752635 185 data\test\pos\880_8.txt
0.921737907046 65 data\test\pos\1617_7.txt
0.915059107274 342 data\test\neg\6931_1.txt
0.90686358907 171 data\test\pos\7620_9.txt
0.903306497024 37 data\test\pos\11657_10.txt
0.899766008797 169 data\test\pos\7457_10.txt
0.897714374058 118 data\test\pos\4872_8.txt

First is probabilities followed by file index and finally the filename.
Anyone else got the same problem?

**Comment by Aceman1982** [comment]
I guess you are taking probabilities only for predicted =1, check for predicted =0 and sort.
 
The values (probas) slightly drift at 6th or 7th decimal places due to floating point precision but the list of file order as per probability are coming precisely as per the order given by professor.

--Vivek

**Comment by nishu2901** [comment]
probability = predicted_proba[s][predicted[s]]


This is how I'm calculating the probability.
Is it wrong?

**Comment by aronwc** [comment]
@nishu2901 are you filtering to documents that were labeled incorrectly? e.g., `predicted[s] != y_test[s]`?

**Comment by nishu2901** [comment]
Don't know what went wrong, but now when I tried it again it comes up correct. Thanks
