### ISSUE TITLE
missing term ( index_of_term(vec, term):)

### ISSUE THREAD

**Issue by czhao18** [iit-cs579/main#114]
def index_of_term(vec, term):
my output of this method is 1614 instead of 1615, is this alright?

**Comment by jaydeeppatel1701** [comment]
error possibility in two methods, do_vectorize and tokenize_with_punct. In your do_vectorize function you have to call two functions. CountVectorizer and fit_transform.

**Comment by czhao18** [comment]
@jaydeeppatel1701 
I got the same result as professor in tokenizer_expt() method, 
but in print(vec.get_feature_names()[:10]) I have following output
[u'!', u'"', u'#', u'$', u'%', u'&', u'(', u')', u'*', u'-']
instead of 
[u'!', u'"', u'#', u'$', u'%', u'&', u'(', u')', u'*', u'+']

**Comment by aronwc** [comment]
@czhao18 does your `tokenize_with_punct` method return '+' characters? (it should) E.g.:

```python
nonascii_string = u'énot the\x85fiancéée-\n\rof not++Henrié '
print 'tokenize:', tokenize(nonascii_string)
print 'with punct:', tokenize_with_punct(nonascii_string)
print 'with not:', tokenize_with_not(nonascii_string)
```
```
tokenize: [u'not', u'the', u'fianc', u'e', u'of', u'not', u'henri']
with punct: [u'\xe9', u'not', u'the', u'fianc', u'\xe9', u'\xe9', u'e', u'-', u'of', u'not', u'+', u'+', u'henri', u'\xe9']
with not: [u'\xe9', u'not', u'not_the', u'not_fianc', u'\xe9', u'\xe9', u'e', u'-', u'of', u'not', u'not_+', u'not_+', u'henri', u'\xe9']
```

**Comment by jaydeeppatel1701** [comment]
Are you getting accuracies of min_df, max_df, tokenize_expt as mentioned by professor? if no means there is a slight variation in these then you should revisit do_vectorize and tokenize_with_punct and if yes then might be the problem in somewhere else. Because it totally depends on how you interpret tokenize_with_punct. Like for last 2-3 days i was able to tokenize strings correctly but not getting correct accuracy. 
You have to figure out which regex professor had used while generating output then and then only you will get the answers as professor got. Otherwise it will be always slight different then professor.
try to use findall and \w and \s

**Comment by czhao18** [comment]
@aronwc @jaydeeppatel1701 
Something wrong with my tokenize_with_punct method, exclude '+', problem solved! Thanks
