### ISSUE TITLE
PROJECT:Memory issues in CountVectorizer

### ISSUE THREAD

**Issue by mamtakanvinde** [iit-cs579/main#138]
I am trying to vectorize terms,using CountVectorizer. Though I have used restrictions in tokenize function like collapse_mentions, collapse_urls, etc, I am still getting a very large set of features and thus runnng into a memory error.
What can I do to fix this? .Can anyone help me out here? Was there a similar problem with anyone else?
Please help

**Comment by aronwc** [comment]
Did you try increasing min_df?
How much data do you have?
If it is a lot, you'll need to stream it from the file, rather than reading
it all in memory, and then calling fit_transform. That is, create a
function that iterates over the file, using the yield
<http://pythontips.com/2013/09/29/the-python-yield-keyword-explained/> keyword
to return each object to be vectorized. Then, pass that function as input
to fit_transform. In this way, each object will be vectorized, then removed
from memory, so you only need to store the sparse matrix.

-Aron

**Comment by mamtakanvinde** [comment]
I have around 10,000 rows right now. If I input 3000-4000 text rows, the countvectorizer works fine. But with 10,000 it does not work atall.
I also am doubtful if there is an issue with my machine. I am working on i3 processor and 4 gb ram.

**Comment by mamtakanvinde** [comment]
yes yield is much faster and its working fine with yield,thanks professor
