### ISSUE TITLE
add_all_friends functionality

### ISSUE THREAD

**Issue by pshah109** [iit-cs579/main#156]
Hi professor can you please explain add_all_friends functionality. Do we need to create a list of user containing dictionary ?

**Comment by ClaytonTurner** [comment]
The add_all_friends function is already taking in a dictionary of users as a parameter to the function

The purpose of this function is to use the get_friends method (as per the comment string under the function def line) in order to retrieve the friends for each of the candidates.

So really you're just wanting to modify the users dictionary that is passed into the function

If you take a look at the main() method at the bottom you'll see that users is already defined before being sent to the add_all_friends method so you just need to add information (i.e. modify) this dictionary to contain a list of followers for each candidate.

**Comment by pshah109** [comment]
Thank a lot Clayton
