### ISSUE TITLE
friend_overlap() doctest complete?

### ISSUE THREAD

**Issue by davidghiurco** [iit-cs579/main#161]
One of the specifications for friend_overlap is that:
"[The] list should be sorted in descending order of N."

Furthermore,
"Ties are broken first by user1's screen_name, then by user2's screen_name"

I want to make sure that the doctest correctly tests the entire functionality of friend_overlap. 

My question is, what is a "tie"? Who/what is tied with who/what? I feel like that specification is a bit vague. I've written the code and gotten the doctest to pass SUCCESSFULLY however I'm not entirely sure that the doctest tests for "ties"

Does it mean that if there are certain tuples that have the same N value, then that tie is broken by alphabetically ordering those tuples according to user1's screen_name? And then if there are tuples that have the same N value and the same user1 screen_name, that tie is broken by alphabetically ordering according to those tuples' user2 screen_name?

If this is the case then I did it correctly, but I want to make sure.

**Comment by saiarjuntanguturi** [comment]
It sounds like you did it correctly, but keep in mind that Profs doc tests don't test every functionality of every function. You could write your own to make sure the behavior is as expected. 

Just because you pass all the doctests doesn't necessarily mean you've met all the expected behavior.

**Comment by ClaytonTurner** [comment]
In the doctest for example, users a & b and users b & c both have 2 in common. I believe this is what is considered to be a tie in this situation.

The first tiebreaker is first screen name that is checked. So in this situation, since the 2 is tied, the first screen name is checked on both, which in the a & b pair is a and in the b & c pair is b. So since the string "a" and string "b" are being compared (and ascending alphabetical order is specified) the a & b pair comes before the b & c pair.

Feel free to add more doctests to check out this behavior.
