### ISSUE TITLE
ValueError: too many values to unpack (expected 2

### ISSUE THREAD

**Issue by sandeep-17IIT** [iit-cs579/main#169]
robust_request(twitter,'users/lookup', screen_names) for method get_users always get me this error. checking the web i am not able to resolve it . pls help

**Comment by thirumalrao** [comment]
Looks like there are more arguments passed than expected . Can u paste the
line that's causing this error ?

**Comment by sandeep-17IIT** [comment]
return robust_request(twitter,'users/lookup', screen_names)
I have not been able to install nose test .. i had debug to find this line in py shell ...
so for twitter.request('users/lookup', screen_names) i still get this error

**Comment by saiarjuntanguturi** [comment]
Check out these issues: 
https://github.com/iit-cs579/main/issues/159#issuecomment-244149470
https://github.com/iit-cs579/main/issues/164#issuecomment-244518090

It is most likely because you're not passing in the arguments to the twitter API correctly. screen_names is a list, while it is looking for a dict with argument name as key, and arguments as values.

**Comment by sandeep-17IIT** [comment]
That works! i should have read the fine print! ....
i got confused looking at screen_names being list at https://dev.twitter.com/rest/reference/get/users/lookup
