### ISSUE TITLE
approximate_betweenness

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#207]
In the formula to calculate betweenness, the denominator is sigma(s,t) which is the number of shortest path between s and t for all V (vertices).

Given that we have made call to bfs and bottom up for each node, how should we go about calculating sigma(s,t) ?

From bfs, we have the number of shortest paths which pass through a vertex BUT for betweenness we are dealing with an edge.

**Comment by davidghiurco** [comment]
You have all the data structures you need. The node2parents dict actually secretely stores information about the total number of paths there are to each node.

If len(node2parents[child] = 50, that's saying that there are 50 parents to this node, and since all parents only get added if they are on the shortest path, that also means that there are 50 shortest paths to that particular node.

Additionally, you need to check the node2num_paths of each individual you are checking.

so sigma, as you call it, or the sum of the number of paths to all the parents would be something like

sum = 0
for parent in parents(node)
sum += node2num_paths[parent]

**Comment by davidghiurco** [comment]
by the way the above calculation should happen in bottom_up not in approximate_betweenness. You calculate betweenness for each node with node n being the root in bottom_up. In approximate_betweenness() all you do is sum up the scores and divide by 2.

**Comment by RittickDatta** [comment]
Thank you David, your explanation is helpful.
