### ISSUE TITLE
path_score

### ISSUE THREAD

**Issue by qsong4** [iit-cs579/main#209]
I get weird result on path_score
<img width="584" alt="screen shot 2016-10-01 at 9 01 25 pm" src="https://cloud.githubusercontent.com/assets/15973873/19018081/46d7a1ec-881a-11e6-81fa-a16d9737dfdf.png">
and my code is:
<img width="664" alt="screen shot 2016-10-01 at 9 02 44 pm" src="https://cloud.githubusercontent.com/assets/15973873/19018085/70258708-881a-11e6-8520-32134a0e9a28.png">
I am not sure if this is ok to post my code here, but I really hope someone can help me.

**Comment by davidghiurco** [comment]
your actual score calculation is wrong. Look at page 353 of the of reading and review the equation. You're not using the correct terms, more specifically the denominator of the calculation in your code is wrong. The denominator needs to be the total number of paths to ALL the PARENTS of the node, not to the node itself.

**Comment by davidghiurco** [comment]
Ignore what I said earlier, I was talking about the wrong function. 

First off, you may want to reconsider using math.inf as the permanent depth limit because as per instructions of the function, path_score needs to have the same runtime complexity as approximate bfs, meaning you're not to search past depth of the node you need. (At least that's what I understand from it).

I'm not sure but it could be the way you're checking for nodes. It's a bit complicated maybe try something like
for node in graph.nodes():
     if node != root and not graph.has_edge(root, node).

The rest looks very similar to what I did and I'm getting the correct output so I don't know why you'd be getting those scores.

**Comment by n-getty** [comment]
Are you sure you want to remove all the neighboring nodes from the graph? This removes all the edges that contain these nodes...

**Comment by theTechie** [comment]
Another weird thing happening for me,

i get exactly the values as in Log.txt for both `jaccard` and `path_score`.

Even the accuracy for `jaccard` is as expected. But for `path_score`, i am getting an accuracy of 0.2 instead of 0.4 (as in Log.txt)

**Comment by qsong4** [comment]
Thank you all! I finally find why I got wrong scores, because I made a mistake on my function bfs. If you have same issue like me, maybe you can check your bfs.

**Comment by qsong4** [comment]
@n-getty Actually this will not removes all  the edges that contain these nodes. I remove all the neighboring nodes because we do not need to check existing edge.
