### ISSUE TITLE
partitions going wrong

### ISSUE THREAD

**Issue by theTechie** [iit-cs579/main#211]
Looks like my partitions are going wrong. I am always getting a cluster of 1 and n-1 nodes.

> _first partition: cluster 1 has 711 nodes and cluster 2 has 1 nodes_

I am guessing i might be doing something wrong in ```bottom_up``` calculation

Anyone faced this before and any other pointers to where might be the problem ?

I am also trying to write some solid doctests to test ```bottom_up```

**Comment by n-getty** [comment]
Are you sorting with reverse = True? Debug and check that the edge you are removing each time is indeed the "right" edge. If this is not the case, the problem is indeed likely in the bottom_up credit value calculations. It is hard to say where you have gone wrong without seeing your algo though I would not show it here. I am not sure to what extent I can help you with it however.

**Comment by qsong4** [comment]
I got the same problem before. I think you can check your BFS, try to change the root to test your BFS.

**Comment by theTechie** [comment]
I verified all methods with extensive tests and all seems fine. 
But, there a problem somewhere for sure ! Still unable to find it :-(

This is the log when i run `partition_girvan_newman(subgraph, 3)`

first partition: cluster 1 has 711 nodes and cluster 2 has 1 nodes
cluster 2 nodes:
['Kula Project']

> i think i might have a very low max_betweenness_score ~ 184

Will revisit this after a break !

**Comment by vmanikes** [comment]
I got the same issue, it is because in the graph you may have same betweenness for multiple edges and might be u r removing only one edge of high betweenness and removing the edge with next highest betweenness. 

So what you need to do is remove edges with the same highest betweenness first and then travese to the next highest betweenness if there are no 2 components


Hope this helps

**Comment by theTechie** [comment]
- `bfs being wrong` - Nope ! I verified my bfs is working fine by comparing my results with `nx.single_source_shortest_path`
- removing edges with highest beweenness also seems to be working as expected
- i also kind of verified `bottom_up` for a different graph (seems to match with my manual calculations)

Still no idea what's wrong 👎 :-(

Can anyone tell me if max_betweenness_score ~ 184 is `correct` or `wrong` ?
(for subgraph with max_depth=3 as used in evaluation)

**Comment by n-getty** [comment]
I get ~980 for depth of 3.

**Comment by theTechie** [comment]
I was damned !!

Unbelievable to find out this was the problem 😱 

I had written an additional functions to get the children of a node:

```python
def get_children(node, node2parents):
    all_children = []

    for n, parents in node2parents.items():
        if node in parents:
            all_children.extend(n)     # this was wrong (on strings) !

    return all_children
```

```python
def get_children(node, node2parents):
    all_children = []

    for n, parents in node2parents.items():
        if node in parents:
            all_children.append(n)     # this is correct !

    return all_children
```

Not a single problem anywhere; just this !!
