### ISSUE TITLE
Final submission queries

### ISSUE THREAD

**Issue by ranjeetkumar** [iit-cs579/main#213]
Hi Prof/TA,
I have two queries.
1) Result of cluster 2 nodes are matching with the provided log. But the ordering of content of cluster 2 nodes that is provided in log are not matching with my result. Is this fine?
2) My whole program is taking around 2 minutes. Is this fine? or do I need more optimization?

Thanks,
Ranjeet

**Comment by joezhang2** [comment]
Regarding 1, someone also asked about that and its ok if the order is not the same: Heres a link for your own reference.
https://github.com/iit-cs579/main/issues/205

I am not sure about the time tho

**Comment by ClaytonTurner** [comment]
I think 2 minutes is a little long. Dr Culotta's solution takes 10-15 seconds. I'm not sure what time you should be really gunning for, but I think it needs to be shorter than that

**Comment by aronwc** [comment]
See #212

**Comment by ranjeetkumar** [comment]
Hi prof/TA,

I am able to reduce my run time from 2 minutes to 45 seconds in my laptop. I can't able to optimize more than this.

I ran my code on amazon ec2 instances. The following are the results 

m4.large : 15 seconds
m4.xlarge: 15 seconds
m4.2xlarge: 13 seconds
m4.4xlarge : 15 seconds

The system configurations of the instances are the following:

![1](https://cloud.githubusercontent.com/assets/1698169/19085864/896c801a-8a89-11e6-8be4-cc6ec58d09e9.png)

I noticed that result is independent of number of cores. It mainly depend on the micro-architecture of the processor. Mine is core 2 duo processor i686 (very old micro-architecture) ,  I think due to this only, it is giving such high value of run time. 

Is my runtime acceptable without penalizing marks for it, as on amazon ec2 it is giving expected runtime?

**Comment by davidghiurco** [comment]
I'm willing to bet anything your code is vastly inefficient. There's
absolutely no reason whatsoever why the entire script would take more than
a minute to run. My solution takes 10 seconds on a modest computer.

Make sure you:
in bfs, are not computing nodes past the maximum depth allowed, AND ARE NOT
CHECKING THE DEPTH BY RUNNING A TRAVERSAL IN AND OF ITSELF. a simple if
statement and lookup in your 3 data structures tells you the depth. if you
have another function that traverses the tree in order to find depth, bingo
you have your culprit.
bottom_up only visits each node once.
partition_girvan_newman only calculates betweenesss scores once. if you are
calling approximate_betweeness in a loop, you're wasting a TON of time,
because it only needs to be calculated once.

P.S. python doesn't automatically distribute its payload to multiple-cores
implicitly. You have to explicitly program each thread and run it on a
certain core to achieve some semblence of parallelism. So you can throw all
the cores you want at it, it's not gonna make much of a difference. Even
python threads actually run concurrently not truly parallel.

**Comment by davidghiurco** [comment]
also if you're using a list in bfs to push and pop to simulate a queue, remember that lists are O(n) lookup because they are made to store information usually "permanently" unlike a stack or a queue. data structures such as a Queue or Deque in python are made specifically to have approximately O(1) push and pop operations. Given the nature of the assignment, O(n) or O(1) in bfs could make a huge difference on time complexity because bfs runs a lot.

**Comment by ranjeetkumar** [comment]
I think generation of processor does matter. My same code run on low end system(m4.large) on amazon ec2 within 15 seconds. m4.large is 2.3 GHz Intel Xeon® E5-2686 v4 (Broadwell) processors or 2.4 GHz Intel Xeon® E5-2676 v3 (Haswell) processors which is newer generation of processor. Mine is very old generation of computer.

**Comment by davidghiurco** [comment]
If you're just looking for excuses to blame on the generation of CPU, I guess that's up to professor or TA to determine. I'm just a student. But I do recommend checking the internals of your algorithm. If you're not using the data structures professor recommended, defaultdict, and deque, you're probably doing a lot of inefficient work.

**Comment by pratik27shah** [comment]
the issue is the complexity of your code is high..may be you have used multiple loops where it was not needed.I recommend you to recheck the alogrithm of BFS and also approximate betweeness

**Comment by ranjeetkumar** [comment]
I have done all the possible optimization by going into details by python profiler. I am stating facts what I observe, I am not looking for excuse. I strongly believe processor family matter a lot.  This is the comparison of family of processor http://www.anandtech.com/show/7003/the-haswell-review-intel-core-i74770k-i54560k-tested/6 . Mine processor is at the bottom of the pyramid

Prof/TA can you please clarify?

**Comment by aronwc** [comment]
Hi all,

I'm glad this has generated some good discussion. I've gotten a number of questions of the form "My code takes X seconds to run; is that fast enough?" Unfortunately, there's really no way for me to answer that without looking closely at your code, which will happen when we grade your assignments.

I think the comments made here and in other issues are helpful. To summarize:
- Computing the approximate betweenness of all edges should be no worse than `O(VE)`, which the book gives as the complexity of the original betweenness algorithm.
- Using Python's profiler can help you find methods that are taking the most time.
- `partition_girvan_newman` should only calculate betweenness once.
- Be sure you understand the complexity of operations for the data structures you're using. Here is a great summary: https://wiki.python.org/moin/TimeComplexity
- One loop is better than two loops, but no loops is better still ;)

**Comment by ranjeetkumar** [comment]
Thanks everyone.
