### ISSUE TITLE
Getting the betweenness value and best edge but not 2 components

### ISSUE THREAD

**Issue by anushamrl** [iit-cs579/main#220]
I'm getting the approximate betweenness and subsequently the best edge from the maximum value. The same edge gets removed from the graph copy but when 'nx.connected_component_subgraphs' is used, just one component is returned. All doc tests pass for the example but does not work for the facebook data. Am I missing anything?

Thanks.

**Comment by vmanikes** [comment]
I got the same issue, it is because in the graph you may have same betweenness for multiple edges and might be u r removing only one edge of high betweenness and removing the edge with next highest betweenness.

So what you need to do is remove edges with the same highest betweenness first and then travese to the next highest betweenness if there are no 2 components

Hope this helps

**Comment by Kirubakumaresh** [comment]
do we need to compute the approximate_betweenness every time we remove the edge or it is just once?

**Comment by aronwc** [comment]
Just once.

**Comment by anushamrl** [comment]
In my case, there is just one highest betweenness edge. Thats why I'm not sure why only one component is getting returned.

**Comment by vmanikes** [comment]
Just remove the edges until you get 2 components.  you have to remove multiple edges but not a single edge

**Comment by anushamrl** [comment]
It worked. Thankyou.
