### ISSUE TITLE
Combinations of Feature Functions

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs579/main#239]
I'm confused how many combinations of Feature Functions we should use. "feature_fns = [token_features, token_pair_features, lexicon_features],
    then we will consider all 4 combinations of features (see Log.txt
    for more examples)."
How are there only 4 combinations here? I would think that we would try all combinations of feature functions upto the length of the list. i.e.
  [(token_features),(token_pair_features),(lexicon_features),(token_features,token_pair_features),(token_pair_features,lexicon_features),(token_features,lexicon_features),(token_features,token_pair_features,lexicon_features)]
which would give us 7 combinations of feature functions to try.

**Comment by ClaytonTurner** [comment]
Reading through the assignment instructions and tampering with my own testing/solution to a smaller version of the problem, I tbelieve you're correct in thinking that there should be 7, **however** I believe Dr Culotta's aim here is for you to have multi-value combinations instead of single item combinations, which would give you 4 valid answers.

For example: combinations of [a,b,c] would be: [a],[b],[c],[a,b],[b,c],[a,c], and [a,b,c]
                     removing the single item elements would yield: [a,b],[b,c],[a,c], and [a,b,c] 

This shows the reduction from 7 to 4. I believe this is what Dr Culotta is asking for, but I'll leave this open for him to correct just in case.

**Comment by saiarjuntanguturi** [comment]
Thank you! I came to the same conclusion, but then I saw this in the Log.txt
"worst cross-validation result:
{'features': (<function lexicon_features at 0x114172d08>,), 'punct': True, 'accuracy': 0.64749999999999996, 'min_freq': 2}"
which uses a single item element.

**Comment by aronwc** [comment]
It should indeed be 7.
See here: https://github.com/iit-cs579/assignments/issues/21

I commit this fix a few days ago:
https://github.com/iit-cs579/assignments/commit/35a69b4d0912577736ee8b5784c01385794215ca

**Comment by saiarjuntanguturi** [comment]
Thanks!

**Comment by pliu19** [comment]
Does it mean that in eval_all_combinations function, there are totally 3 * 2 * 7 = 42 experiments to run??
