### ISSUE TITLE
Issues with output

### ISSUE THREAD

**Issue by kyao4** [iit-cs579/main#259]
Hi, everyone

This is my my output:
```
best cross-validation result:
{'min_freq': 2, 'features': (<function token_pair_features at 0x7fec0e047488>, <function lexicon_features at 0x7fec0e047510>), 'punct': True, 'accuracy': 0.76749999999999996}
worst cross-validation result:
{'min_freq': 10, 'features': (<function lexicon_features at 0x7fec0e047510>,), 'punct': True, 'accuracy': 0.65000000000000002}
```

It is obviously not consistent with the log.txt, but I checked all the functions related to this output, everything looks fine,all the doctests are passed. so in which part can be wrong given this output? Anyone can help?

**Comment by davidghiurco** [comment]
I have a similar question in #262 but my output is just ordered differently than professor's Log.txt. My accuracies match. It seems that yours don't.

What I suggest is that you check your tokenize() method that you are removing both leading and ending external punctuation (so "?!;$#test's?!:.#" should tokenize to "test's") because if you don't check for leading external punctuation, you will pass the doctest for tokenize since there are no tokens with leading punctuation, but it's possible to get them in the test data.

I can't give any other suggestions without looking at your code unfortunately

**Comment by kyao4** [comment]
I just check the leading and ending external puncuation with my tokenize, it still passed the doctest, so I think something else should be wrong. Thanks anyway.

**Comment by davidghiurco** [comment]
Another case i just thought of where passing the doctest may be misleading
is in token_pairs where if you check combinations of the list, it will pass
since the list only has 3 elements but you're actually supposed to checking
rolling sliders aka "window iterators" over the list.

On Oct 17, 2016 11:44 PM, "Kai Yao" <notifications@github.com> wrote:

I just check the leading and ending external puncuation with my tokenize,
it still passed the doctest, so I think something else should be wrong.
Thanks anyway.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/iit-cs579/main/issues/259#issuecomment-254405489>, or mute
the thread

**Comment by kyao4** [comment]
I just modified my regular expression for the tokenize and then I get correct accuracy. Just as you said, even if the doctest for tokenize is passed, it is not ensured that is correct for the training data and testing data.Thanks David
