### ISSUE TITLE
minfreq in vectorize

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#261]
I have dictionaries for each document. Each document has different number of features/words. Now should I compare frequencies within a document dictionary to min frequency or compare minfreq to occurence of that feature in each document.

If minfreq = 3, does it mean that the feature has to occur in at least 3 documents or it has to occur 3 times in a single document?

Some conceptual clarity would help.

**Comment by davidghiurco** [comment]
as per instructions:
      min_freq......Remove features that do not appear in
                    at least min_freq different documents.

to answer your question, min_freq is the minimum number of documents a feature has to be part of in order to be considered in the vocabulary. min_freq ,is NOT the minimum total frequency of the occurance of each feature.

So if feature x appears 5 times in doc1 and 0 times in doc2, and 1 time in doc3, min_freq = 2

**Comment by RittickDatta** [comment]
Thank you David.
