### ISSUE TITLE
eval_all_combination running time 

### ISSUE THREAD

**Issue by KSP16SCM52J** [iit-cs579/main#264]
Running time for eval_all_combination is quite high around 2-3  mins. Any tip to optimize the running time. I have revisited the vectorize function and found that the major running bottleneck is updating row,col and data for csr_matrix.My for loops are majorly of the order of O(n^2).

**Comment by vmanikes** [comment]
Even the same thing for me bro. It is taking a long time

**Comment by aronwc** [comment]
`vectorize` should take O(n), where n is number of tokens.
As we discussed in class, it's probably best to first create data/row/col variables, then create the csr_matrix and return it.

**Comment by davidghiurco** [comment]
eval_all_combinations can really waste alot of time if you're tokenizing the docs more than 2 times. You should only tokenize 2 times at most. One time for keep_internal_punct=True and the other time for keep_internal_punct=False.

**Comment by thirumalrao** [comment]
vectorize takes unusually long time only when the feature_fn is token_pair_features. I understand this feature function will return more tokens than others, but the difference in performance is huge.
For example, for token_features - vectorize takes ~4-5seconds, for token_pair_feature it takes upto 100 seconds for min_freq = 2.
computing csr data(looping over tokens and checking for minimum frequency criteria) is taking lot of time, but I have made it near O(N). 
Anyone else facing this issue ? Could be a trivial mistake in loop due to oversight, but haven't been able to figure out yet.

**Comment by davidghiurco** [comment]
It definitely is not supposed to take that long with token_pair_features.

http://stackoverflow.com/questions/6822725/rolling-or-sliding-window-iterator-in-python

I bet you're doing some inefficient work in your token_pair_features loops.
See this stackoverflow link for clues as to how to implement the sliding
window.

And yes checking min_freq should take O(N) time if you use a data structure
to store all the frequencies (like a dict)

**Comment by thirumalrao** [comment]
token_pair_features itself is not taking long. It's vectorize method that computes csr rows and columns that's taking time. 
Correct me if I am wrong, if the number of tokens is n, then number of windows is n-2, and number of features will be 3(n-2). After going through the counter, its roughly 2n.

So, for token_pair_features(tokens, feats) -- if len(tokens) is 300, then len(feats) could be roughly 600.. right ?

Also, for filling values for csr rows, columns and data - I am looping through the tokens, and checking each token if its above min_freq. Looks like this check is adding lot of delays.

**Comment by davidghiurco** [comment]
See that's the thing you're very wrong. lol
Consider list [a, b, c]
Windows of size 1 are [a], [b], [c]
windows of size 2 are [a,b], [b,c]
window of size 3 is [a,b,c]

Also for min_freq....again. That is not O(n). If you're checking frequency each time in a loop that will be o(n^2). You need to trade time complexity for space complexity and iterate ONCE over all the tokens and store each frequency in a data structure (preferably a dict, for fast lookup). Then you will have O(n) time complexity and O(n) space complexity

**Comment by joezhang2** [comment]
@thirumalrao, assuming that the data structure @davidghiurco mentions has been completed, you can't avoid looking up each vector to check if it is in the data structure. From what I understand set operations are faster than iterating in Python, so you could try finding the intersection between the vectors of a token and your vocab dictionary instead of iterating through each token.

For the token_pairs, the number of windows is n-k+1, where k = size of the window. The number of pairs per window is k-1 + (k-2)+(k-3)+... or (k-1)(k)/2. So the number of pairs we examine under a brute force approach is: (n-k+1)* ((k-1)(k)/2), given k is small in relation to n, its O(n) complexity. You can improve upon a brute force approach slightly by pre-calculating the overlaps that we know will occur, reducing the number of pairs per window but it's still O(n). 

For example if we have the token: [a, b, c, d, e] and k is 3, the output is: ab=1, ac=1, bc=2, bd=1, cd=2, ce=1, de=1. So the token values next to each other will appear multiple times depending on the size of the window and we could derive some algorithm to predict this. But lets say our token is [a,b,c,a,b], the output is now ab=2, ac=1, bc=2, ba=1, ca=2, cb=1. These overlaps in the token cannot be predicted and so we are forced to iterate it regardless of any algorithm and deal with the O(n) complexity.

**Comment by thirumalrao** [comment]
Thanks  @davidghiurco for your advise. 
@joezhang2 -- Thanks for your detailed explanation. My understanding seems to be correct. 
Looks like the issue is fixed.
