### ISSUE TITLE
Lexicon Features

### ISSUE THREAD

**Issue by saiarjuntanguturi** [iit-cs579/main#272]
Hi,

In lexicon features, the description says : "Add features indicating how many time a token appears that matches either the neg_words or pos_words (defined above). The matching should ignore case."

However, since we take care of case in our tokenize function, wouldn't matching ignore case be redundant? Very minor issue, but I'm debugging, and just noticed. Thanks!

**Comment by ranjeetkumar** [comment]
When we run complete program, then it doesn't matter. When we don't apply ignore case inside lexicon features  then individual doctest of lexicon_features will fail. 

doctest of lexicon_features
>>> feats = defaultdict(lambda: 0)
    >>> lexicon_features(np.array(['i', 'LOVE', 'this', 'great', 'boring', 'movie']), feats)
    >>> sorted(feats.items())
    [('neg_words', 1), ('pos_words', 2)]
LOVE is in uppercase, so that will result in failure of the doctest.

I think, in complete run of the program this lower case conversion is redundant.

**Comment by ClaytonTurner** [comment]
I think it's a good idea to take care of this in both places as functions are sometimes tested as stand-alone functions. In the context of your main() it may never hit that case, but in the context of unit testing it could.

**Comment by davidghiurco** [comment]
Ignoring case is a matter of unit testing. That's where tokens may be capitalized. But you are correct, tokenize passes in only lowercase tokens
