### ISSUE TITLE
eval_all_combinations

### ISSUE THREAD

**Issue by RittickDatta** [iit-cs579/main#278]
Hi, 
Has anyone faced this error while calling csr_matrix() 

ValueError: cannot infer dimensions from zero sized index arrays.

My vectorize method passed all doctests.

**Comment by vmanikes** [comment]
Did you check if your row,data,column has data or not?

**Comment by RittickDatta** [comment]
If i change the min_freq value to 1, i get correct csr matrix but for min_freq = 2, i get above error.

I am only passing 2 documents: ["Isn't this movie great", "Horrible, horrible movie"]

**Comment by vmanikes** [comment]
It is correct, that should not be a problem

**Comment by RittickDatta** [comment]
If I increase the documents to 3, I have no issues.
["Isn't this movie great", "Horrible, horrible movie", "Isn't this movie great"]

Is this a corner case and would not affect results on the actual documents ?

**Comment by davidghiurco** [comment]
Solution: make sure you are passing the "shape=" parameter to your csr_matrix()

**Comment by RittickDatta** [comment]
In my eval_all_combination method, I have lot of nested loops to enumerate the different cases. I tokenized outside the loop, that reduces some nesting but combinations of feature_fns is complicating the nested loop. How can I reduce nested loops further?

**Comment by davidghiurco** [comment]
You need at least 4 nested loops:
Nest 1: punctuation values
        Nest 2: tokenize
        Nest 2: min_freq values
                   Nest 3: all combination lenghts
                            Nest 4: all combinations of particular length

You can do this manually or using product() which does this internally

**Comment by vmanikes** [comment]
@davidghiurco What does the `shape=` parameter do?

**Comment by RittickDatta** [comment]
@davidghiurco Won't until "Nest 3" cover all the cases ? I think we can avoid "Nest 4".

**Comment by davidghiurco** [comment]
@RittickDatta no because you need combinations of length 1, combinations of length 2, combinations of length 3.

More specifically you need all possible length combinations of the feature functions. Assuming you're using the builtin "combinations" library, that library requires a combination length parameter. You're trying multiple length combinations not just one so you need to loop over all different combination lengths and use the currect combination length you're looking at to iterate over all combinations of that length and do stuff with that combination.

Either way you do it, you will still need to nest 2 loops to iterate over all length combinations. Whether you do that explicitly or use a built-in library other than "combinations"

**Comment by davidghiurco** [comment]
Shape=(num_rows, num_columns)
