### ISSUE TITLE
Tokenize doctest issue

### ISSUE THREAD

**Issue by ddabhane** [iit-cs579/main#289]
When I run doctest for my tokenize method, the output is perfect but I am finding it difficult to understand why my doctest is failing.
<img width="550" alt="screen shot 2016-10-20 at 6 28 23 pm" src="https://cloud.githubusercontent.com/assets/16137159/19585043/bf03bf68-970e-11e6-802e-ecaa0b4be794.png">
<img width="502" alt="screen shot 2016-10-20 at 6 36 10 pm" src="https://cloud.githubusercontent.com/assets/16137159/19585045/c153de06-970e-11e6-9b31-35dbaefa5e22.png">

**Comment by davidghiurco** [comment]
you are missing a trailing whitespace (I had this problem too where my IDE was removing trailing whitespace from end of all lines). It turns out that the result of printing the array actually includes a whitespace right after the very last comma after the array elements are done.

so in your doctest:
    >>> tokenize("??necronomicon?? geträumte sünden.<br>Hi", False)
    array(['necronomicon', 'geträumte', 'sünden', 'br', 'hi'],(NEED WHITESPACE RIGHT HERE)
          dtype='<U12')

**Comment by ddabhane** [comment]
@davidghiurco I tried that but still it fails.
<img width="554" alt="screen shot 2016-10-20 at 9 55 25 pm" src="https://cloud.githubusercontent.com/assets/16137159/19585202/0a1c5c02-9710-11e6-85f0-e5ec43c52232.png">

**Comment by davidghiurco** [comment]
No you misunderstood what I said.

You're not supposed to delete the newline in your doctest. You're supposed to add a whitespace before that newline:

    >>> tokenize(" Hi there! Isn't this fun?", keep_internal_punct=False)
    array(['hi', 'there', 'isn', 't', 'this', 'fun'],(WHITESPACE)(NEWLINE)
          dtype='<U5')
    >>> tokenize("Hi there! Isn't this fun? ", keep_internal_punct=True)
    array(['hi', 'there', "isn't", 'this', 'fun'],(WHITESPACE)(NEWLINE)
          dtype='<U5')
    >>> tokenize("??necronomicon?? geträumte sünden.<br>Hi", True)
    array(['necronomicon', 'geträumte', 'sünden.<br>hi'],(WHITESPACE)(NEWLINE)
          dtype='<U13')
    >>> tokenize("??necronomicon?? geträumte sünden.<br>Hi", False)
    array(['necronomicon', 'geträumte', 'sünden', 'br', 'hi'],(WHITESPACE)(NEWLINE)
          dtype='<U12')

**Comment by ddabhane** [comment]
@davidghiurco I tried again, but failed. 
<img width="515" alt="screen shot 2016-10-20 at 10 07 44 pm" src="https://cloud.githubusercontent.com/assets/16137159/19585418/df629e20-9711-11e6-95ec-1d5f261c33f6.png">
Hope i didn't misunderstood this time.

**Comment by davidghiurco** [comment]
At this point I honestly wouldn't worry about it. You're getting every correct output, it's just a matter of trailing whitespaces that are invisible in expected output that are mismatching with the actual output you get. If you wanna spend more time looking for where that trailing whitespace should be (or should not be) you're welcome to, but know that you're not failing your doctest because your function is wrong necessarily, but because there's characters in your expected output that shouldn't be in there.

One thing you could do is copy and paste the doctests from the template branch.

**Comment by ddabhane** [comment]
@davidghiurco Thanks. Every time i tried I copied and paste from template.

**Comment by ClaytonTurner** [comment]
See this issue for more information, but it probably isn't a big deal: https://github.com/iit-cs579/main/issues/238
