### ISSUE TITLE
Getting weird error in vectorize method

### ISSUE THREAD

**Issue by kartikaygautam** [iit-cs579/main#291]
the error : -

<img width="574" alt="screen shot 2016-10-20 at 9 53 31 pm" src="https://cloud.githubusercontent.com/assets/21162800/19585154/b3c4a918-970f-11e6-8eb5-baa85e78c99a.png">

**Comment by kartikaygautam** [comment]
been getting this god forsaken error since yesterday !! :P

**Comment by aronwc** [comment]
I'm not sure what else is going on in your code, but I don't think you want to computing currentIndexOccurence using the .index method. This does a linear search through tokens_list to find the matching docTokens. Instead, you can use enumerate when looping through tokens_list to get the current index. E.g.:

```python
for i, tokens in enumerate(tokens_list):
  # do something with i and tokens
```

**Comment by kartikaygautam** [comment]
basically what i am trying to do is to count the number of docs/sublists in which a particular element occurs, this is so that i can prune away the tokens that dont occur in >= min_freq docs.

the way i set out to do this was simple : -

moving left to right through the array, store the doc index where the particular token was encountered, a.k.a currentIndexOccurence, now when the same word is encountered again check if the current doc_index is different (basically > since going from left to right in tokens_list) from when the element was last encountered,

if yes then def this is a new doc and therefore simply increment the doc_freq value of the particular word

then later i can prune away whatever is not needed.

however i cannot even get the index of my document :/ 

although i have worked around the problem using a variation of the implementation , im still lost as to why this is happening. 

also i havent thought about many test cases but assuming there are no duplicate documents, i dont think this approach should have any drawbacks. 

all ears to any suggestions/critique of my approach .

**Comment by davidghiurco** [comment]
@kartikaygautam I recommend you use a dictionary whose keys are feature names and whose values are frequency of those particular features. Also don't traverse the feature list using index lookup. Just use pythonic for each loops. 
2 reasons:
1) Looking up the frequency to see if it's >= min_freq is fast because value lookups in dicts are fast
2) If you store indicies, your lookup times for each feature frequency is absolutely going to kill your perfomance (it will take a VERY long time for eval_all_combinations to finish) because you will essentially be doing O(n) lookup for EVERY FEATURE. since every time you want to find the frequency you have to do linear search for a particular index
