### ISSUE TITLE
make_predictions issue

### ISSUE THREAD

**Issue by pratik27shah** [iit-cs579/main#339]
While calculating cosine if my cosine addition for the movies is 0.0 then my weighted avg=(Avg ratings of the movie) or should it be 0.0?
eg:
Cosine of (Finding Nemo,Batman)=0
(Finding Nemo,Conjuring)=0
but the rating of batman=3.5 and Conjuring is 4 so the weighted average=(3.5+4)/2=3.75

and am I suppose to ignore the values for which the cosine is negative:
eg:
Cosine of (Finding Nemo,Avatar)=-1
(Finding Nemo,Toy Story)=0.5
rating of Avatar=4,Toy Story=5,weighted average=((0.5*5))/0.5 and ignoring the values of avatar completely as its cosine is negative.

**Comment by joezhang2** [comment]
The professor also added a new commit to the assignment repo which explains how to handle you get 0's for the cosine similarity between every movie in training set and your test movie. It seems like you are doing it correctly: 
>     If there are no other movies with positive cosine similarity to use in the
    prediction, use the mean rating of the target user in ratings_train as the
    prediction.

You can also look at the [assignments](https://github.com/iit-cs579/assignments/blob/master/a3/a3.py) repo and/or update your local repository for this.

You shouldn't be getting any negative values for the cosine similarity. The numerator is a dot product between two vectors where every vector component is >= 0. We know this because the way we calculate tfidf results in every value being greater or equal to 0, so the dot product will also be greater or equal to 0. 
Likewise, the denominator of the cosine similarity is the product of two magnitudes which are always positive. I'd suggest creating a unit test for your cosine_similarity function to see if it is working properly.
