### ISSUE TITLE
Solution for bonus quiz

### ISSUE THREAD

**Issue by thirumalrao** [iit-cs579/main#382]
Hi Prof,
Could you please post the solution to the quiz?

**Comment by saiarjuntanguturi** [comment]
For the first question, you're given the initial means, and the points you are tying to cluster:
    mean 0: (1, 0)
    mean 1: (4, 0)
points:
    point 0: (0, 2) => mean 0 since (1-0)^2 + (0-2)^2 = 5, (4-0)^2 + (0-2)^2 = 20,  and 20>5
    point 1: (0, 1) => mean 0 since (1-0)^2 + (0-1)^2 = 2, (4-0)^2 + (0-1)^2 = 17, and 17>5
    point 2: (2, 0) => mean 0 since (1-2)^2 + (0-0)^2 = 1, (4-2)^2 + (0-0)^2 = 4, and 4>1
    point 3: (3, 1) => mean 1 since (1-3)^2 + (0-1)^2 = 5, (4-3)^2 + (0-1)^2 = 2, and 5>2
    point 4: (3, 0) => mean 1 since (1-3)^2 + (0-0)^2 = 4, (4-3)^2 + (0-0)^2 = 1, 4>1

For the second question, we recompute the means based on the points we've assigned to each cluster:
mean 0 = (point1 + point2 + point3)/3 = ( (0+0+2)/3, (2+1+0)/3) = (0.667, 1.000)
mean 1 = (point4 + point5)/2 = ( (3+3)/2, (1+0)/2) = (3.000, 0.500)

For the third question,
`import math
def calc_distance(list1,list2):
    dist = 0
    for i in range(len(list1)):
        dist += (list1[i]-list2[i])**2
    return math.sqrt(dist)
mean_vec1 = [2/3,1]
mean_vec2 = [3,0.5]
sum = 0
clus1 = [[0,2],[0,1],[2,0]]
clus2 = [[3,1],[3,0]]
for each in clus1:
    sum += calc_distance(each,mean_vec1)
for each in clus2:
    sum += calc_distance(each,mean_vec2)
print(sum)`

Your final answer should be : 4.535

Feel free to run the above Python code. Basically we calculate the distances between each point and it's assigned mean, and we add each distance to the total sum. The distance formula is what we did for questions 1 to 5, but we care about the sqrt for the sum. For the first question, it was not necessary to compute sqrt of the totals since we were simply deciding between two clusters, and the greater sum of the squares of the differences meant that the distance was greater.

**Comment by thirumalrao** [comment]
thanks
