### ISSUE TITLE
About the program running time

### ISSUE THREAD

**Issue by ZihanNiu** [iit-cs579/main#405]
Will it take a long time to run after the function get_subgraph? my code runs well before the get_subgraph function. After return the subgraph, it looks like running forever. I tried to change the min_degree value to 30, soon there was a result. I wondered is it supposed to be take a long time to run or just my code has some problem?

**Comment by SanchayanMaity** [comment]
How long are you talking about exactly? I believe the running time should not be more than a minute for the complete code no matter what. There is an old closed issue ticket on this as well. I have yet to implement evaluate and normalisation cut related functions but currently except for the last part in main, till jaccard calculation it runs under 30 seconds for me. Perhaps someone does even better than that.

**Comment by ZihanNiu** [comment]
I can't have results after return the subgraph

**Comment by SanchayanMaity** [comment]
So the partition_girvan_newman implementation of yours probably has some bug or perhaps one of the later functions called? Did you try using pdb to pinpoint the location of perhaps where it is continuously looping?

**Comment by aagrekar** [comment]
I tried using partition_girvan_newman implementation as done by professor (removing the recurrsion part) and it is taking 35-40 mins to run. So, to find what function was taking long I reduced my scope to approximate_betweenness() and ran that in the loop for max_depth 1-4, and that completed in just a 10 secs, so I think what it depends on is the girvan_newman algorithm.. 

As per the algorithm, the betweenness has to be calculated over and over again after removing each nodes until you get two partitions. So, it is surely going to run long as there are many edges to be removed to get 2 clusters.

I tried it in another way..! I kept on removing edges with higher betweenness until 2 clusters were obtained but calculated the betweenness only once.. and this completed in around 12 secs.

So, I am not sure about which one is correct.! because my results didn't match even in both the cases.

The max_depth and normalized cut value for depth 2 might have some problem ( I am not sure though) but my values are matching for max_depth = 1, 3 and 4.

Any help here would be appreciated.!

**Comment by RonitRudra** [comment]
Ankush Agrekar, your implementation is correct.

According to the docstring of the *partition_girvan_newman* function, the betweenness is to be calculated only once so you do not need to recompute it by calling it after each edge removal. I understand the actual algorithm asks for recomputation after edge removal but my implementation conforms with what is mentioned in the function docstring. Maybe, that is why the function is called *approximate_betweenness()* as it does not follow the actual algorithm.

Therefore, just call *approximate_betweenness* once and then keep removing edges till you get 2 components. I called it only once and my output matches the sample output of *log.txt*

**Comment by SanchayanMaity** [comment]
@aagrekar As Ronit also points out, in partition_girvan_newman, approximate_betweenness has to be called only once and not on each node removal. The only thing you loop should be doing in there is removing edge till you get two clusters. Also refer the PDF notes.
