### ISSUE TITLE
Adamic/Adar score for Quiz

### ISSUE THREAD

**Issue by SanchayanMaity** [iit-cs579/main#412]
Can someone elaborate how was the Adamic/Adar score calculated for the question in quiz with A and B having C and D as common friends and C having 10 and D having 100 neighbours?

**Comment by nith1989** [comment]
![adamic adar score](https://user-images.githubusercontent.com/21175545/31286864-1dbd65e2-aa85-11e7-9fb1-2623e17a76bf.jpg)

**Comment by SanchayanMaity** [comment]
@nith1989 Thanks. I understood where I went wrong.

**Comment by EFA16SCM55A** [comment]
Be careful if you see there are different between equations or concepts and the code, you have to watch the lecture because the professor mentioned the reason behind that as I remembered. For example, this question if you used the code without paying attention for the professor's explanation, you will get wrong. I'm worried about the midterm there is 4(T/F) and 6 short answers and if you get one wrong, you will lose many points! 
Good luck

**Comment by SanchayanMaity** [comment]
I made the mistake of trying to interpret the solution from the code instead of a direct application of the equation, assuming I did not intepret the code wrong. " if you used the code without paying attention for the professor's explanation, you will get wrong" << Ya, this is what happened in my case I believe and I lost 8 marks. Makes me worry about the midterm as well. I rather write 3 more coding assignments any time of day than give an exam. Coding clears things up better and is more fun..

**Comment by aronwc** [comment]
Indeed, there was a bug in my adar implementation. 

```python
score = sum(math.log10(len(list(graph.neighbors(o))))
                    for o in neighbors & neighbors2)
```
should be
```python
score = sum(1/math.log10(len(list(graph.neighbors(o))))
                    for o in neighbors & neighbors2)
```
I've gone back through the quiz and given you credit if you used that implementation (so, the answer would be 3 in that example above)

**Comment by SanchayanMaity** [comment]
@aronwc  Yes, my answer was indeed 3. Thank you very much for considering this :).
