### ISSUE TITLE
log.txt and the output of A2

### ISSUE THREAD

**Issue by c830g420** [iit-cs579/main#428]
Do we need to print the exactly same result as log.txt? 
Since the cross validation randomly splits testing and training set, every time I change the random-state, the result changes.

**Comment by aronwc** [comment]
I discussed this during lecture yesterday.

**Comment by EFA16SCM55A** [comment]
I have the same issue but also with the values, and I couldn't figure out what make my data is not look like the output in the log.txt:
My output look like that:
{'features': (<function token_pair_features at 0x000001C36AD68730>, <function lexicon_features at 0x000001C36AC686A8>), 'punct': False, 'accuracy': 0.76249999999999996, 'min_freq': 2}
worst cross-validation result:
{'features': (<function lexicon_features at 0x000001C36AC686A8>,), 'punct': True, 'accuracy': 0.64749999999999996, 'min_freq': 10}
Mean Accuracies per Setting:
features=token_pair_features lexicon_features: 0.74167
features=token_features token_pair_features lexicon_features: 0.73750
features=token_features token_pair_features: 0.73083
features=token_pair_features: 0.72708
min_freq=2: 0.71929
punct=False: 0.71726
min_freq=5: 0.71536
punct=True: 0.70560
features=token_features lexicon_features: 0.70042
min_freq=10: 0.69964
features=token_features: 0.69500
features=lexicon_features: 0.64750

TOP COEFFICIENTS PER CLASS:
negative words:
neg_words: 0.58492
token_pair=the__worst: 0.40019
token_pair=is__so: 0.31182
token_pair=about__the: 0.26844
token_pair=like__a: 0.25577

positive words:
pos_words: 0.42179
token_pair=it__is: 0.24418
token_pair=i__think: 0.22848
token_pair=and__it: 0.21597
token_pair=to__find: 0.21310
testing accuracy=0.735000

TOP MISCLASSIFIED TEST DOCUMENTS:
truth=1predicted=0probas=0.989680753763
In defense of this movie I must repeat what I had stated previously.......
truth=1predicted=0probas=0.985864737931
There I was on vacation when my host suggested we take in this B-Movie festival in Breda. I was resistant, as I hadn't gone.....
truth=1predicted=0probas=0.983486005149
Being a freshman in college, this movie reminded me of my relationship with my mom. Of course, my situation doesn't parrallel with Natalie ....... 
truth=0predicted=1probas=0.981794540428
I absolutely despise this film. I wanted to love it - I really wanted to. But man, oh man - they were SO off with Sara. And the father .......
truth=1predicted=0probas=0.980052915523
I went into this film expecting a slasher, and while Mute Witness does take influence from said style of film-making, this is much more than just your average slash flick. There are a number of thrillers that focus on a certain disability......
Please, if anyone get the same results and figure out what the problem is , just direct me to which function I has to focus on to solve this problem.
Thanks

**Comment by SyedHamdanSher** [comment]
you are getting almost the right output, u just need to sort the result properly, we are printing result[0] and result[-1] , the correct accuracy values are there in the result but at diff index value. Mine was at result[-3], solution is sorting the result properly

**Comment by EFA16SCM55A** [comment]
Thank you so much, I didn't consider min_freq when I sorted b/c nothing about in the instruction which mentioned just sorting the accuracy.

I figure out that if any one find punct is different from the log, it means your tokenize function need to be fix.
If the coefficients per class is different, look also in lexicon_features if you are sure your function for top_coeff is correct.  I was considering for ignoring counting each pos or neg word that appear again in the list, so I wrote couple of lines to make sure from that but after I removed this condition and make it count each pos or neg word will appear in doc, I got the same result in the log and the test accuracy won't be longer higher and will be the same.
