### ISSUE TITLE
Log Result comparison isn't the same

### ISSUE THREAD

**Issue by Cheths** [iit-cs579/main#431]
I'm getting slightly different results with respect to settings and accuracies compared to the sample log.

The **testing accuracy is 0.752500 ** better compared to the sample log result. So, should I worry about **matching the results to the sample log**?

best cross-validation result: accuracy: 0.76250000000000007
worst cross-validation result: 0.64749999999999996

Note: I've listened to the Lecture on 10/23.

Is anyone facing the same issues?

**Comment by shashravi9** [comment]
Even I am getting the slight variations in the results. Also, the testing accuracy 0.7475 which is better than the given log result.

**Comment by SyedHamdanSher** [comment]
I add similar issue but the solution to this problem is sorting the result properly, we are printing result[0] for the best case and result[-1] for the worst case, I printed the entire result DS to find out where the correct ans lies, I found out the matching values to the log file where present in the result but at diff location. mine was at result[-3]. I sorted correctly and now my ans match with the log.

I hope this helps
