### ISSUE TITLE
tf(i, d) and max_k tf(k, d)

### ISSUE THREAD

**Issue by pmedrano1** [iit-cs579/main#433]
In this case, if I am getting it right, if tf(i, d) is the frequency of term i in document d and the terms are the genre/s of the document(movie in this case), each of them will only appear once in each document(movie) so tf(i, d) will be 1 in every case. Then if max_k tf(k, d) is the maximum frequency of any term in document d and a term only appears once per document max_k tf(k, d) will also always be 1.
That is how I was thinking but I am not completely sure if it is right if someone could confirm it I would appreciate it.
Thanks

**Comment by EFA16SCM55A** [comment]
I think the answer will be like that
Document1: This is my car.
Document2: This problem is impossible.
The rule is as the following:
tfidf(i, d) := tf(i, d) / max_k tf(k, d) * log10(N/df(i))
tf(This , Document1)=1
tf(is  , Document1)=1
tf(my , Document1)=1
tf(car , Document1)=1
max_k tf(This| is |my |car,  Document1) =1
N=2  (number all the documents we have)
df(This)=2 (this appears two times in all the document)
tfidf(This , Document1) := 1 / 1 * log10(2/2)=0
This is just example that I make to help you to see if this impossible case happens,  just select the max.
if my understanding is incorrect, please correct me.
Good luck

**Comment by lzq100123** [comment]
I think tf(i,d)/max_k will always be 1/1 since the term comes from genres, and it's impossible to have duplicate terms for one movie like "comedy | comedy"

**Comment by pmedrano1** [comment]
@EFA16SCM55A yeah I think your example is right although I was't thinking about the tfidf value only tf and max_k so what do you mean when you say just select the max? What would we have to do to avoid getting tfidf value zero?
What I was actually asking was what @lzq100123 says I wasn't sure if it was like that.
Thanks both of you

**Comment by EFA16SCM55A** [comment]
I know what you means by looking in the real world example, for sure you are right.
 However, if I tried to make it has duplicate terms, it works.  We talk about documents that can have repeated terms.
movies = pd.DataFrame([[123, 'comedy | comedy'], [456, 'Sci-Fi']], columns=['movieId', 'genres'])
movies = tokenize(movies)
movies['tokens'].tolist()
[['comedy', 'comedy'], ['sci-fi']]
The result will return a duplicate term and I didn't face any trouble if I make genres have duplicate terms.

I mean that just select the maximum an move on. For example, I have the values[1,1,2,3,3] select the max of them 3 and move on.

**Comment by nerdySingh** [comment]
i have the same question also is the vocab in featurize of size 21?

**Comment by SanchayanMaity** [comment]
In featurize what is used for the 'term'? Is it the 'title' column or 'genres' column from the movies data frame?

**Comment by SanchayanMaity** [comment]
@nerdySingh Yes for me, vocab in featurize has 21 values.

**Comment by SanchayanMaity** [comment]
In featurize, during calculation of tf-idf what is 'd'? Is it the 'title' column of movies or is it 'tokens'? So is the movie title to be considered or genres? I am getting a bit confused here.

**Comment by lzq100123** [comment]
@SanchayanMaity see #432 , I just asked the same question

**Comment by SanchayanMaity** [comment]
@lzq100123 Thanks for the pointer. Wasn't sure on proceeding further.

**Comment by ckomurluiit** [comment]
Only items in the tokens column will be considered for featurize as answered by Prof. Culotta previously. As these tokens come from genres column.

Your tf/max_k tf interpretation is correct. It should result 1 for each term, unless there is repetition. Note that this is not the complete TF-IDF formula. There is also log(N/df(i)) part.

Finally, Some people stated that vocab has 21 elements, which I disagree on. Mine has 22 elements. Are you talking about the max column index, or the total number of elements in that dictionary?

**Comment by SanchayanMaity** [comment]
@ckomurluiit Thanks for confirming the number of elements in vocab. In fact, mine had 20 and noticed it incorrectly earlier. Turns out my tokenize implementation was wrong and I was also not using tokenize_string. Fixed it and it is 22 now.

**Comment by nerdySingh** [comment]
so let's say we have a list ['Comedy','Drama','Thriller']
i = Comedy
d= "Toy Story"
tf(i,d) = 1 as Comedy comes only once,
max_k tf(k,d) = 1
N = 9125 as there are these many rows in the document.

and df(i) is the total no of times Comedy comes in all the 9125 rows or we have to count "toy story as 1 document only?"

because my 1st csr_matrix looks like this -:
[ 1.09627522  0.76340228  0.83712529  2.27402274  0.87362558]

just want to know if this is correct or not!

**Comment by ckomurluiit** [comment]
According to Prof Culotta's remark on uniqueness (see #320 ), you have to refer to movieId to detect unique instances/movies in the `movies` data frame.

In addition, I believe that your 1st csr_matrix length should be larger, as its dimensions need to be 1 x num_features. And num_features need to be equal to the length of your `vocab`.
