### ISSUE TITLE
CSR Matrix - num_features length 

### ISSUE THREAD

**Issue by chinths89** [iit-cs579/main#436]
In featurize the description says '"Each row will contain a csr_matrix of shape (1, num_features)" The num_features is it equal to the total number of genres across all movies, or only for that movie. I think it would make sense to calculate the length as the total number of genres across all movies so that cosine similarity will correctly calculate for corresponding genres.

**Comment by ckomurluiit** [comment]
I agree on that otherwise, cosine similarity will never be calculated as csr_matrix dimensions can easily be different. More precisely, dot product cannot be calculated for two vectors of different sizes.

Moreover, consider this case: Suppose we have two movies, each with three genres. One has `['children', 'family', 'comedy']` and the other has `['adventure', 'war', 'thriller']`. Also suppose, all these tokens have high tf-idf values. If we do not use the overall number of features as num_feature for their csr_matrices, their cosine similarity will be very high, although these two movies are highly dissimilar. However, when they share the same num_feature, their dot product will be zero (e.g. the first has a non-zero value for comedy, but the other has 0, so their product will be 0. Similarly, the first one has 0 for 'war' but the other one has a non-zero value, so their product will be 0.), hence their cosine similarity will be 0.

**Comment by chinths89** [comment]
Yes thanks !!!

**Comment by mdrews93** [comment]
This is still confusing me a bit. If the size of the csr matrix is the length of the vocabulary, then what's the point in creating the csr matrix in the first place? I thought the length of the csr matrix of each movie will be the same length as the number of genres for that movie, as that's how many non-zero tf-idf weights there will be for that movie.

And we can still take the cosine similarity because the csr matrix also contains the indices of the features from the data list, so in computing the similarity, you'll only take the product of two weights if they have a matching index.

**Comment by ckomurluiit** [comment]
> This is still confusing me a bit. If the size of the csr matrix is the length of the vocabulary, then what's the point in creating the csr matrix in the first place? I thought the length of the csr matrix of each movie will be the same length as the number of genres for that movie, as that's how many non-zero tf-idf weights there will be for that movie.

In my opinion, that is how using a sparse representation (`csr_matrix`) makes more sense. Otherwise, for all movies, only non-zero tf-idf values would exist and we could easily use dense matrix representation (`np.ndarray`).

> And we can still take the cosine similarity because the csr matrix also contains the indices of the features from the data list, so in computing the similarity, you'll only take the product of two weights if they have a matching index.

I am confused. If you create a csr_matrix for a movie only using genres of that movie, how are the csr_matrix indices going to be global? Global in the sense that for example `thriller` is always 18th element in csr_matrices across all movies.

**Comment by mdrews93** [comment]
Maybe to be more clear, for each movie I first create the dense 1D matrix where the index of each genre's weight is given by the vocab. This 1D matrix is of size (1, num_genres). But then I convert it to a csr matrix and add that csr matrix to the dataframe. 

So the actual size of each csr matrix is not a universal (1, num_features), but rather it's the number of genres for that particular movie. And the indices list contains the indices of each genre in the vocab, so if a movie contains the `thriller` genre and let's say that `thriller` is the 18th genre in the vocab, then each csr matrix that contains a weight for thriller will also store that corresponding index.
