### ISSUE TITLE
read_graph() method

### ISSUE THREAD

**Issue by FatemaT** [iit-cs579/main#57]
in the read_graph method what exactly are the edges connecting? the like between the users and their friends? or is it something else because connecting those doesn't have the same number of edges and nodes as given in the provided result. I know which nodes to add but i don't know what am i supposed to connect with the edges.

**Comment by carolgrrr** [comment]
I believe the edges are returned from the snowball function. If I understand this correctly, the edges dictionary maps each user id A to list of user ids B1,B2,..., where A likes B.

**Comment by aronwc** [comment]
Correct. The edges in `edges.txt` indicates that "A likes B". For this assignment, we'll assume that likes are symmetric, so "A likes B" implies "B likes A". You'll read `edges.txt` into an undirected graph in networkx.

Because of the symmetry, some of the edges are duplicated in `edges.txt`. E.g.:
```
$ egrep '^TED\s*TEDx$' edges.txt 
TED	TEDx
$ egrep '^TEDx\s*TED$' edges.txt 
TEDx	TED
```

Thus, while there are 6,173 lines in `edges.txt`:
```
$ wc -l edges.txt 
    6173 edges.txt
```
there are only 6,060 edges in the resulting undirected graph.

-Aron
